#!/usr/bin/env python3
"""Random S3 activity simulator for the FAM lab.

Reads the actors generated by 05-create-actors.sh and loops forever, having
a random actor perform a random action (PUT, GET, LIST, DELETE, or a
presigned-GET fetched via curl) against the source bucket. Stops cleanly
on Ctrl+C / SIGTERM and prints a per-action summary.
"""
import argparse
import json
import os
import random
import signal
import string
import subprocess
import sys
import time
from datetime import datetime, timezone

import boto3
from botocore.exceptions import ClientError


def _source_env_sh(path: str) -> None:
    """Source a bash env script and import its exports into os.environ.

    Spawns bash to source `path`, prints the resulting env as NUL-delimited
    KEY=VALUE pairs, then merges keys we don't already have set. Existing
    env vars win so inline overrides (`FOO=bar python3 ...`) keep priority.
    """
    if not os.path.isfile(path):
        return
    try:
        out = subprocess.check_output(
            ["bash", "-c", f'set -a; . "{path}"; env -0'],
            stderr=subprocess.DEVNULL,
        )
    except (OSError, subprocess.CalledProcessError):
        return
    for entry in out.split(b"\x00"):
        if not entry or b"=" not in entry:
            continue
        k, _, v = entry.decode("utf-8", "replace").partition("=")
        if k and k not in os.environ:
            os.environ[k] = v


_source_env_sh(os.path.join(os.path.dirname(os.path.abspath(__file__)), "00-env.sh"))

ACTIONS = ["put", "get", "list", "delete", "presigned_get"]
ACTION_WEIGHTS = [40, 25, 10, 5, 20]  # PUT highest so GET/DELETE have content

ERROR_ACTIONS = [
    "denied_acl",
    "denied_bucket_policy",
    "denied_other_bucket",
    "denied_prefix",
    "missing_key",
    "expired_presign",
    "view_once",
    "tampered_presign",
]

EXTENSIONS = [".txt", ".xml", ".json"]
CONTENT_TYPES = {
    ".txt": "text/plain",
    ".xml": "application/xml",
    ".json": "application/json",
}
PREFIXES = ["documents/", "reports/", "configs/", "exports/", "uploads/"]
# Prefixes only privileged-tier actors can read/write. Must match the explicit
# Deny in 05-create-actors.sh.
RESTRICTED_PREFIXES = ["restricted/", "confidential/"]
RESTRICTED_PUT_PROBABILITY = 0.2  # chance a privileged actor PUTs into restricted/
WORDS = ["alpha", "beta", "gamma", "delta", "epsilon", "zeta", "eta",
         "theta", "iota", "kappa", "lambda", "mu", "nu", "xi"]

_running = True


def _stop(_sig, _frame):
    global _running
    _running = False
    print("\n[!] Stop requested. Finishing in-flight action...", flush=True)


signal.signal(signal.SIGINT, _stop)
signal.signal(signal.SIGTERM, _stop)


def random_body(ext: str) -> bytes:
    label = "".join(random.choices(string.ascii_lowercase, k=6))
    ts = datetime.now(timezone.utc).isoformat()
    if ext == ".txt":
        lines = [
            " ".join(random.choices(WORDS, k=random.randint(4, 12)))
            for _ in range(random.randint(3, 10))
        ]
        return ("\n".join(lines) + f"\n# {label} {ts}\n").encode()
    if ext == ".xml":
        items = "\n".join(
            f'  <item id="{i}">{random.randint(1, 9999)}</item>'
            for i in range(random.randint(2, 8))
        )
        return (
            f'<?xml version="1.0"?>\n<doc owner="{label}" generated="{ts}">\n'
            f"{items}\n</doc>\n"
        ).encode()
    if ext == ".json":
        payload = {
            "owner": label,
            "generated": ts,
            "values": [random.randint(1, 1000) for _ in range(random.randint(3, 10))],
        }
        return json.dumps(payload, indent=2).encode()
    return b""


def random_key(restricted: bool = False) -> str:
    prefix = random.choice(RESTRICTED_PREFIXES if restricted else PREFIXES)
    name = "".join(random.choices(string.ascii_lowercase + string.digits, k=8))
    return f"{prefix}{name}{random.choice(EXTENSIONS)}"


def make_client(actor: dict, region: str, endpoint_url: str | None = None):
    return boto3.client(
        "s3",
        aws_access_key_id=actor["access_key_id"],
        aws_secret_access_key=actor["secret_access_key"],
        region_name=region,
        endpoint_url=endpoint_url,
    )


def seed_known_keys(s3, bucket: str, limit: int = 500) -> list:
    keys = []
    paginator = s3.get_paginator("list_objects_v2")
    for page in paginator.paginate(Bucket=bucket):
        for obj in page.get("Contents", []):
            keys.append(obj["Key"])
            if len(keys) >= limit:
                return keys
    return keys


def _curl_status(url: str) -> str:
    try:
        r = subprocess.run(
            ["curl", "-sS", "-o", "/dev/null", "-w", "%{http_code}", url],
            capture_output=True, text=True, timeout=30,
        )
        return r.stdout.strip() or "??"
    except subprocess.TimeoutExpired:
        return "timeout"


def _tamper_signature(url: str) -> str:
    marker = "X-Amz-Signature="
    idx = url.find(marker)
    if idx < 0:
        return url
    pos = idx + len(marker) + 8  # somewhere inside the 64-char hex signature
    c = url[pos]
    swap = "0" if c != "0" else "1"
    return url[:pos] + swap + url[pos + 1:]


def do_put(s3, bucket, known_keys, actor):
    restricted = (actor.get("tier") == "privileged"
                  and random.random() < RESTRICTED_PUT_PROBABILITY)
    key = random_key(restricted=restricted)
    ext = os.path.splitext(key)[1]
    body = random_body(ext)
    s3.put_object(Bucket=bucket, Key=key, Body=body, ContentType=CONTENT_TYPES[ext])
    known_keys.append(key)
    if len(known_keys) > 500:
        known_keys.pop(0)
    tag = " [restricted]" if restricted else ""
    return f"PUT    {key}  ({len(body)} B){tag}"


def do_get(s3, bucket, known_keys, _actor):
    if not known_keys:
        return "GET    skipped (no known keys yet)"
    key = random.choice(known_keys)
    resp = s3.get_object(Bucket=bucket, Key=key)
    resp["Body"].read()
    return f"GET    {key}"


def do_list(s3, bucket, _known_keys, _actor):
    prefix = random.choice(PREFIXES) if random.random() < 0.7 else ""
    resp = s3.list_objects_v2(Bucket=bucket, Prefix=prefix, MaxKeys=20)
    return f"LIST   prefix='{prefix}'  ({resp.get('KeyCount', 0)} keys)"


def do_delete(s3, bucket, known_keys, _actor):
    if not known_keys:
        return "DELETE skipped (no known keys yet)"
    key = known_keys.pop(random.randrange(len(known_keys)))
    s3.delete_object(Bucket=bucket, Key=key)
    return f"DELETE {key}"


def do_presigned_get(s3, bucket, known_keys, _actor):
    if not known_keys:
        return "PRESIGN skipped (no known keys yet)"
    key = random.choice(known_keys)
    url = s3.generate_presigned_url(
        "get_object",
        Params={"Bucket": bucket, "Key": key},
        ExpiresIn=300,
    )
    return f"PRESIGN {key}  (curl -> HTTP {_curl_status(url)})"


def err_denied_acl(s3, bucket, known_keys, _other, _actor):
    key = random.choice(known_keys) if known_keys else random_key()
    try:
        s3.get_object_acl(Bucket=bucket, Key=key)
        return f"DENIED-ACL    {key}  (UNEXPECTED 200 OK)"
    except ClientError as e:
        code = e.response.get("Error", {}).get("Code", "?")
        return f"DENIED-ACL    {key}  (expected {code})"


def err_denied_bucket_policy(s3, bucket, _known, _other, _actor):
    try:
        s3.get_bucket_policy(Bucket=bucket)
        return f"DENIED-POLICY {bucket}  (UNEXPECTED 200 OK)"
    except ClientError as e:
        code = e.response.get("Error", {}).get("Code", "?")
        return f"DENIED-POLICY {bucket}  (expected {code})"


def err_denied_other_bucket(s3, _bucket, _known, other_bucket, _actor):
    if not other_bucket:
        return "DENIED-OTHER  skipped (no --other-bucket configured)"
    try:
        s3.list_objects_v2(Bucket=other_bucket, MaxKeys=5)
        return f"DENIED-OTHER  {other_bucket}  (UNEXPECTED 200 OK)"
    except ClientError as e:
        code = e.response.get("Error", {}).get("Code", "?")
        return f"DENIED-OTHER  {other_bucket}  (expected {code})"


def err_denied_prefix(s3, bucket, _known, _other, actor):
    # Regular-tier actor tries to GET an object in restricted/ or confidential/.
    # The explicit Deny in the actor's policy returns AccessDenied attributed
    # to this specific user — the realistic "snooping" pattern for FAM.
    if actor.get("tier") != "regular":
        return "DENIED-PREFIX skipped (need regular-tier actor)"
    key = random_key(restricted=True)
    try:
        s3.get_object(Bucket=bucket, Key=key)
        return f"DENIED-PREFIX {key}  (UNEXPECTED 200 OK)"
    except ClientError as e:
        code = e.response.get("Error", {}).get("Code", "?")
        return f"DENIED-PREFIX {key}  (expected {code})"


def err_missing_key(s3, bucket, _known, _other, _actor):
    key = f"missing/{''.join(random.choices(string.ascii_lowercase, k=12))}.txt"
    try:
        s3.get_object(Bucket=bucket, Key=key)
        return f"MISSING-GET   {key}  (UNEXPECTED 200 OK)"
    except ClientError as e:
        code = e.response.get("Error", {}).get("Code", "?")
        return f"MISSING-GET   {key}  (expected {code})"


def err_expired_presign(s3, bucket, known_keys, _other, _actor):
    if not known_keys:
        return "EXPIRED-LINK skipped (no known keys yet)"
    key = random.choice(known_keys)
    url = s3.generate_presigned_url(
        "get_object", Params={"Bucket": bucket, "Key": key}, ExpiresIn=1,
    )
    time.sleep(2)
    return f"EXPIRED-LINK  {key}  (curl -> HTTP {_curl_status(url)})"


def err_view_once(s3, bucket, _known, _other, _actor):
    # Simulate a "view-once" link: PUT, presign, view, delete object, retry view.
    # S3 has no native single-use URLs; deleting the object is the standard trick.
    key = random_key()
    ext = os.path.splitext(key)[1]
    s3.put_object(
        Bucket=bucket, Key=key, Body=random_body(ext), ContentType=CONTENT_TYPES[ext]
    )
    url = s3.generate_presigned_url(
        "get_object", Params={"Bucket": bucket, "Key": key}, ExpiresIn=300,
    )
    first = _curl_status(url)
    s3.delete_object(Bucket=bucket, Key=key)
    second = _curl_status(url)
    return (f"VIEW-ONCE     {key}  "
            f"(first HTTP {first}, retry-after-delete HTTP {second})")


def err_tampered_presign(s3, bucket, known_keys, _other, _actor):
    if not known_keys:
        return "TAMPERED-LINK skipped (no known keys yet)"
    key = random.choice(known_keys)
    url = s3.generate_presigned_url(
        "get_object", Params={"Bucket": bucket, "Key": key}, ExpiresIn=300,
    )
    return (f"TAMPERED-LINK {key}  "
            f"(curl -> HTTP {_curl_status(_tamper_signature(url))})")


DISPATCH = {
    "put": do_put,
    "get": do_get,
    "list": do_list,
    "delete": do_delete,
    "presigned_get": do_presigned_get,
}

ERROR_DISPATCH = {
    "denied_acl": err_denied_acl,
    "denied_bucket_policy": err_denied_bucket_policy,
    "denied_other_bucket": err_denied_other_bucket,
    "denied_prefix": err_denied_prefix,
    "missing_key": err_missing_key,
    "expired_presign": err_expired_presign,
    "view_once": err_view_once,
    "tampered_presign": err_tampered_presign,
}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    default_actors = os.environ.get(
        "FAM_ACTORS_FILE",
        os.path.join(
            os.environ.get(
                "DATA_DIR",
                os.path.abspath(os.path.join(os.path.dirname(__file__), "data")),
            ),
            "actors.json",
        ),
    )
    parser.add_argument("--actors", default=default_actors,
                        help="Path to actors.json from 05-create-actors.sh")
    parser.add_argument("--bucket", default=os.environ.get("FAM_SOURCE_BUCKET"),
                        help="Source bucket (defaults to $FAM_SOURCE_BUCKET)")
    parser.add_argument("--region", default=os.environ.get("AWS_DEFAULT_REGION", "us-east-1"))
    parser.add_argument("--endpoint-url",
                        default=os.environ.get("AWS_ENDPOINT_URL"),
                        help="S3 endpoint URL (e.g. http://localhost:4566 for "
                             "floci/LocalStack). Defaults to $AWS_ENDPOINT_URL.")
    parser.add_argument("--min-sleep", type=float, default=1.0)
    parser.add_argument("--max-sleep", type=float, default=5.0)
    parser.add_argument("--error-rate", type=float, default=0.15,
                        help="Fraction of iterations that simulate a failure "
                             "(AccessDenied, NoSuchKey, expired/tampered/view-once "
                             "presigned URLs). 0.0 disables.")
    parser.add_argument("--other-bucket",
                        default=os.environ.get("FAM_LOG_DESTINATION_BUCKET"),
                        help="Bucket actors should NOT have access to, used for "
                             "cross-bucket AccessDenied simulation. Defaults to "
                             "$FAM_LOG_DESTINATION_BUCKET.")
    args = parser.parse_args()

    if not args.bucket:
        sys.exit("FAM_SOURCE_BUCKET not set and --bucket not provided")
    if not 0.0 <= args.error_rate <= 1.0:
        sys.exit("--error-rate must be between 0.0 and 1.0")

    try:
        with open(args.actors) as f:
            actors = json.load(f)["actors"]
    except FileNotFoundError:
        sys.exit(f"{args.actors} not found - run 05-create-actors.sh first")

    tier_counts = {}
    for a in actors:
        t = a.get("tier", "unknown")
        tier_counts[t] = tier_counts.get(t, 0) + 1
    tier_summary = ", ".join(f"{n} {t}" for t, n in sorted(tier_counts.items()))
    endpoint_label = args.endpoint_url or "default AWS"
    print(f"Loaded {len(actors)} actors ({tier_summary}). "
          f"Target: s3://{args.bucket} ({args.region}) via {endpoint_label}")
    print(f"Sleep range: {args.min_sleep:.1f}-{args.max_sleep:.1f}s between actions.")
    print(f"Error rate: {args.error_rate:.0%}"
          + (f"  (cross-bucket target: s3://{args.other_bucket})"
             if args.other_bucket else "  (no --other-bucket configured)"))
    print("Ctrl+C to stop.\n", flush=True)

    clients = {a["name"]: make_client(a, args.region, args.endpoint_url) for a in actors}

    seed_client = next(iter(clients.values()))
    try:
        known_keys = seed_known_keys(seed_client, args.bucket)
        print(f"Seeded {len(known_keys)} existing key(s) from s3://{args.bucket}.",
              flush=True)
    except ClientError as e:
        code = e.response.get("Error", {}).get("Code", "?")
        print(f"Could not seed keys ({code}); starting with empty list.", flush=True)
        known_keys = []

    counters = {a: 0 for a in ACTIONS}
    err_counters = {a: 0 for a in ERROR_ACTIONS}
    errors = 0
    iter_no = 0

    regular_actors = [a for a in actors if a.get("tier") == "regular"]

    while _running:
        iter_no += 1
        simulate_error = random.random() < args.error_rate
        if simulate_error:
            action_label = random.choice(ERROR_ACTIONS)
        else:
            action_label = random.choices(ACTIONS, weights=ACTION_WEIGHTS, k=1)[0]

        # denied_prefix requires a regular-tier actor (privileged ones won't be denied).
        if simulate_error and action_label == "denied_prefix" and regular_actors:
            actor = random.choice(regular_actors)
        else:
            actor = random.choice(actors)
        s3 = clients[actor["name"]]
        tier_tag = (actor.get("tier", "?")[0] or "?").upper()
        try:
            if simulate_error:
                msg = ERROR_DISPATCH[action_label](
                    s3, args.bucket, known_keys, args.other_bucket, actor
                )
                err_counters[action_label] += 1
            else:
                msg = DISPATCH[action_label](s3, args.bucket, known_keys, actor)
                counters[action_label] += 1
            print(f"[{iter_no:05d}] {actor['name']}({tier_tag})  {msg}", flush=True)
        except ClientError as e:
            errors += 1
            code = e.response.get("Error", {}).get("Code", "?")
            print(f"[{iter_no:05d}] {actor['name']}({tier_tag})  {action_label.upper()} ERROR {code}", flush=True)
        except Exception as e:
            errors += 1
            print(f"[{iter_no:05d}] {actor['name']}({tier_tag})  {action_label.upper()} ERROR {e}", flush=True)

        # Use small sleep increments so Ctrl+C is responsive.
        deadline = time.monotonic() + random.uniform(args.min_sleep, args.max_sleep)
        while _running and time.monotonic() < deadline:
            time.sleep(0.1)

    summary = "  ".join(f"{a}={n}" for a, n in counters.items())
    err_summary = "  ".join(f"{a}={n}" for a, n in err_counters.items())
    print(f"\nStopped after {iter_no} iterations.")
    print(f"  Actions:    {summary}  unexpected_errors={errors}")
    print(f"  Simulated:  {err_summary}")


if __name__ == "__main__":
    main()



