[SERVICE]
    Flush        5
    Daemon       Off
    Log_Level    debug
    Parsers_File parsers.conf

[INPUT]
    Name              tail
    Path              /var/lib/docker/containers/3aa52bff2cfc7cb500500e616d39b1f8cfbc603958ff5f56a238a76a4ec1b70b/*.log
    Parser            java
    Tag               ged-tomcat
    Refresh_Interval  5
    Rotate_Wait       30
    Mem_Buf_Limit     50MB
    Skip_Long_Lines   On
    Docker_Mode       On

#[FILTER]
#    Name   parser
#    Match  ged-tomcat
#    Key_Name log
#    Parser java_multiline

[OUTPUT]
    Name              opensearch
    Match             ged-tomcat
    Host              opensearch-api.gfsolucoesti.com.br
    Port              443
    HTTP_User         admin
    HTTP_Passwd       1qaz@WSX3edc
    tls               On
    tls.verify        On           # Set to On if using a trusted cert
    tls.verify_hostname On
    tls.ca_file       /fluentbit/etc/ca.cert
    Index             ged-tomcat-logs
    Logstash_Format   Off
    Type              _doc
    Suppress_Type_Name On
    Replace_Dots      On