# geneate self signed certs
#openssl req \
#  -newkey rsa:4096 -nodes -sha256 -keyout registry-domain.key \
#  -addext "subjectAltName = DNS:custom-registry" \
#  -x509 -days 365 -out registry-domain.crt
#run: docker-compose up -d --force-recreate
#get credentials from: cat /root/.docker/config.json

version: '3'

services:
  registry:
    container_name: registry
    restart: always
    image: registry:2
    ports:
    - "5000:5000"
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
      REGISTRY_AUTH_HTPASSWD_PATH: /opt/auth/registry.password
      #REGISTRY_HTTP_TLS_CERTIFICATE: /opt/certs/registry-domain.crt
      #REGISTRY_HTTP_TLS_KEY: /opt/certs/registry-domain.key
    volumes:
      - /opt/docker-registry/data:/var/lib/registry
      - /opt/auth:/opt/auth
      - /opt/certs:/opt/certs

  registry-web:
    container_name: registry-web
    restart: always
    image: hyper/docker-registry-web
    links: 
      - "registry"
    ports: 
      - "8080:8080"
    environment:
      REGISTRY_TRUST_ANY_SSL: "true"
      REGISTRY_URL: https://registry:5000/v2
      REGISTRY_BASIC_AUTH: "change_after_get_credentials"
